### ISSUE TITLE
Request Homepage

### ISSUE THREAD

**Issue by Adhaaz** [streamamos/streamamos#1]
![IMG_20230702_135533](https://github.com/streamamos/streamamos/assets/75169859/26c05481-03d7-4775-a24b-09cb8cb429bf)

Sir @streamamos , I would like to make a request, can the homepage layout be like this?

**Comment by Adhaaz** [comment]
@streamamos Please sir 🙏

**Comment by streamamos** [comment]
Hey bro, regarding your first comment (before edited). This is just a static website using an api, i don't control the sources. And in regards to the homepage layout, i'm not really a big fan of those layouts that you need to scroll down in order to see more movies. I made them a slider because it looks cleaner.
